spring.application.name=documentos-spring
spring.mongodb.uri=mongodb://localhost:27018/documentos
spring.mongodb.database=documentos

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

